### ISSUE TITLE
Constructor Function Mismatch

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-tweet-shortener#10]
Out of the box, the lab looks like this:

```
var tweetShortener = {
    wordSubstituter: function(){},
    bulkShortener: function(){},
    selectiveShortener: function(){},
    shortenedTruncator: function(){},
};
```
This suggests to students that we should build the constructor functions in to the object directly instead of using the prototype construction (which we learned was a better practice). If we change things around to use the prototype constructor:
```
function TweetShortener(){}

TweetShortener.prototype.wordSubstituter = function(tweet){
}

TweetShortener.prototype.bulkShortener = function(tweets){
}

TweetShortener.prototype.selectiveShortener = function(tweet){
}

TweetShortener.prototype.shortenedTruncator = function(tweet){
}
```

we understandably get an error because `tweetShortener` that is bing called on in the tests no longer exists:
```
ReferenceError: tweetShortener is not defined
```

Fix:
Add this line to every test to create a new object with the constructor function and use the alias `tweetShortener` which the test already uses:
```
var tweetShortener = new TweetShortener()
```

**Comment by pletcher** [comment]
Hi @onyoo, thanks for reporting this issue. I'm going to close this issue because it's actually fine to use the object-literal definition that this lab expects (and it's an important thing to discover about JavaScript).

If I understand your question correctly, you're referring to the difference between

```js
function TweetShortener() {
  this.wordSubstituter = function() { ... }
  // etc.
```

and

```js
function TweetShortenter() {};

TweetShortener.prototype.wordSubstituter = function() { ... }
// etc.
```

And you're right, the second method is the preferred way to define them. When we use object literals, however, we don't need to instantiate a whole class/prototype and assign methods to that -- instead, we can just pass the object around and call its methods directly without any redundancy or constructors (except the bare `Object` constructor that gets called when we instantiate our literal (`{}`)).

I'm going to take a look at previous lessons to make sure that this approach comes up as an acceptable form of object-orientation in JavaScript -- thanks for bringing it up!

**Comment by onyoo** [comment]
@pletcher Thanks for the explanation. I was confused why we should use the object-literal, when we just learned that it was not the preferred way. However, your explanation makes perfect sense. Thanks!
